name: Lint and Prettier

on:
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node modules
        run: npm ci

      - name: Lint
        run: npm run lint:check

      - name: Prettier
        run: npm run prettier:check

  jest:
    needs: lint-and-prettier
    uses: ./.github/workflows/jest.yml
