name: Pull request into dev, main

on:
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  checkout-and-setup:
    uses: deluxanMD/fantastic-react-app/.github/workflows/setup-node.yml@main

  lint-and-prettier:
    runs-on: ubuntu-latest
    needs: checkout-and-setup
    steps:
      - name: Lint
        run: npm run lint:check

      - name: Prettier
        run: npm run prettier:check
