name: Playwright Tests
on:
  workflow_call:

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Code Coverage
        run: npm run report

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: Upload reports to codecov
          fail_ci_if_error: true
          verbose: true

      - run: |
          set -e
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          find . -iregex "codecov.*"
          chmod +x codecov 
          ./codecov -t ${CODECOV_TOKEN}
          rm codecov

      # - name: Generate lcov report
      #   run: npx nyc report --reporter=lcovonly

      # - name: Upload to Coveralls
      #   uses: coverallsapp/github-action@v2.3.0
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN  }}
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
